name: Auto Merge Main into Feature Branch

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  auto-merge:
    if: contains(github.event.pull_request.labels.*.name, 'autoupdate')
    runs-on: ubuntu-latest
    permissions:
        contents: read
        issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Fetch all branches
        run: git fetch origin

      - name: Checkout the feature branch
        run: git checkout ${{ github.event.pull_request.head.ref }}

      - name: Merge main into feature branch
        run: git merge --squash origin/main

      - name: Commit changes
        if: success()  
        run: git commit -m "Merge main into ${{ github.event.pull_request.head.ref }}"
        
      - name: Push changes
        if: success()
        run: git push origin ${{ github.event.pull_request.head.ref }}
        
      - name: Add comment to PR
        if: success()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = ${{ github.event.pull_request.number }};
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: 'The main branch has been successfully merged into this feature branch! :rocket:'
            });

      - name: Add sad comment to PR
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = ${{ github.event.pull_request.number }};
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: 'The main branch cannot be merged into the feature branch without your help :cry:'
            });
