name: Auto Merge Main into Feature Branch

on:
  push:
    branches:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ♼ Update PRs
        uses: actions/github-script@v7
        id: my-script
        with:
          result-encoding: string
          retries: 3
          script: |
                const { data: pullRequests } = await github.rest.pulls.list({
                    base: 'main',
                    sort: 'updated',
                    state: 'open',
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                })
                const labeledPullRequests = pullRequests.filter(pr => pr.labels.filter(label => label.name == 'autoupdate').length > 0)

                for (let pr of labeledPullRequests) {
                    try {
                        result = await github.rest.pulls.updateBranch({
                            owner: 'amagyar-iohk',
                            repo: 'auto-merge',
                            expected_head_sha: pr.head.sha,
                            pull_number: pr.number,
                        });
                    } catch (err) {
                        core.info(err);
                    }
                }